connections:
  sftp:
    kind: sftp
    host: "${sftp_host}"
    port: ${sftp_port}
    username: "${sftp_username}"
    password: "${sftp_password}"
    keyFile: "${sftp_keyfile}"
    knownHosts: "$System.getProperty('user.home')/.ssh/known_hosts"
