name: "default"

runner:
  kind: logged
  connection: flowman_runs
  retries: 3
  timeout: 1000

connections:
  flowman_runs:
    driver: $System.getenv('FLOWMAN_LOGDB_DRIVER', 'org.apache.derby.jdbc.EmbeddedDriver')
    url: $System.getenv('FLOWMAN_LOGDB_URL', $String.concat('jdbc:derby:', $System.getenv('FLOWMAN_HOME'), '/logdb;create=true'))
    username: $System.getenv('FLOWMAN_LOGDB_USER', '')
    password: $System.getenv('FLOWMAN_LOGDB_PASSWORD', '')

config:
  - spark.sql.warehouse.dir=/opt/flowman/hive/warehouse
  - hive.metastore.uris=
  - javax.jdo.option.ConnectionURL=jdbc:derby:;databaseName=/opt/flowman/hive/db;create=true
  - datanucleus.rdbms.datastoreAdapterClassName=org.datanucleus.store.rdbms.adapter.DerbyAdapter

plugins:
  - flowman-example
  - flowman-hbase
  - flowman-kafka
  - flowman-jdbc
